#     You are given n words. Some words may repeat. For each word, output its number of occurrences. The output order should correspond with the input order of appearance of the word. 

# First line of input contains the total number of words n. Next n lines contain words that need to processed.

# First line of the output should contain the total number distinct words. Second line of output must contain the frequency of words the same order of their appearance as in the input

# Method 1

In [100]:
li=['abcd','ijkl','abcd','pqrs','abcd']
mylist = list(dict.fromkeys(li))
print(mylist)
word=[]
for i in range(len(mylist)):
    count=0
    for j in range(0,len(li)):
        if(mylist[i]==li[j]):
            count=count+1
    word.append(count)
print(word)
        
    

['abcd', 'ijkl', 'pqrs']
[3, 1, 1]


# Method 2

In [35]:
li=['abcd','ijkl','abcd','pqrs','abcd']
print(li.count('abcd'))

3


# Define a function to validate email addresses based on the following rules.¶

   * Email should be in the format username@domain.extension
   * username must start with an alphabet and can contain lowercase alphabet, digits, hyphen(-) and underscores( _ ).
   * username must not contain special characters, uppercase letters, whitespaces.
   * Length of username must be in the range (6, 16)
   * Domain can only contain lowercase alphabet and digits with length in range (3, 10) . No special characters are allowed
    * Extension can only contain lower case alphabet and its length must be in the range (2, 4)



In [132]:
import re
def isValidEmail(email):
     if (6 < len(email) <= 16):
        if re.match("^[a-z]{6,16}[0-9]{2,3}[@][a-z]{3-10}[.][a-z]{2,4}$",email):
             return True
        return False
if isValidEmail("sandeepjordan1230@gmail.com") == True :
    print("This is a valid email address")
else:
    print("This  is not a valid email address")

This  is not a valid email address


# 3 . Define a function that take an array of integers A, and an integer K and returns the longest possible sub-set of A i.e A' such that the sum of no two elements in A' is divisible by K.

* First line in input contains the length of A and the integer K. Second line of input contains len(A) space-separated integers.

* Output must contain the length of A' list

* Sample Input : 4 3

* 1 7 2 4

* Sample Output : 3

In [159]:
def subsets(n,k):
    q=[]
    count=0
    for i in range(len(li)):
        for j in range(i+1,len(li)):
            sum=li[i]+li[j]
            if(sum%k!=0):
                count=count+1
    print(count)
li=[1,7,2,4]
k=int(input("enter"))
subsets(li,k)

enter3
3


# 4.Python program to add two matrices.

In [176]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,5,6])
c=a+b
print(c)




[3 7 9]


# Disarium or not

In [133]:
def Disarium(n):
    count=len(str(n))
    sum=0
    q=n
    while(n!=0):
        n=n%10
        p=n**count
        sum=sum+p
        count=count-1
        n=n//10
    if(sum==q):
        print("Disarium")
    print("Not Disarium")
Disarium(13)
    

Not Disarium


# Python program to print all Happy Numbers between 1 to 100. 

In [18]:
for i in range(1,100):
    sum1=0
    num=i
    while(sum1!=1 and sum1!=4):
        sum1=0
        while(num>0):
            p1=num%10
            p2=p1**2
            sum1=sum1+p2
            num=num//10
        num=sum1
    if(sum==1):
        print(num)

    

    
        
        

# Traspose of a matrix

In [25]:
import numpy as np
a=np.array([[1,2,3],[11,12,13],[21,22,23]])
print("Before Tranpose :")
print(a)
print("After Transpose :")
print(a.transpose())

Before Tranpose :
[[ 1  2  3]
 [11 12 13]
 [21 22 23]]
After Transpose :
[[ 1 11 21]
 [ 2 12 22]
 [ 3 13 23]]


# Python program to  remove punctuations from a string.

# Method 1

In [ ]:
def Punctuation(string): 
    b = ''',@'''
    for x in string.lower(): 
        if x in b:
            string = string.replace(x, "") 

    print(string) 
string = "Sandeep@jordan,m"
Punctuation(string) 


# Method 2

In [90]:

s = 'abc12321cba,safa,safds,as'

print(s.translate({ord(','): None}))


abc12321cbasafasafdsas
